# https://github.com/realm/SwiftLint
included:
  - Sources
type_name:
  min_length: 2
variable_name:
  min_length:
    warning: 2
line_length: 160
disabled_rules:
  - control_statement
  - unused_closure_parameter
